apiVersion: v1
kind: Service
metadata:
  name: api-cloud-gateway-service
spec:
  selector:
    app: api-cloud-gateway  # Debes ajustar esto según las etiquetas de tus pods
  ports:
    - protocol: TCP
      port: 8080         # Puerto del servicio dentro del clúster
      targetPort: 8080   # Puerto en el contenedor del microservicio
  # type: LoadBalancer         # Accedido solo en el cluster
  type: NodePort
